### ISSUE TITLE
Questions on labels and tests

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#147]
1. Is it a goal to support multiple labels? TinkerPop3 [does not support multiple labels](http://tinkerpop.apache.org/docs/current/reference/#_multi_label):

    > TinkerPop3 requires every Element to have a single, immutable string label (i.e. a Vertex, Edge, and VertexProperty).

    I can imagine the TinkerPop property graph model as a basis for potential openCypher implementations, so this seems an important design decision. The [acceptance tests](https://github.com/opencypher/openCypher/blob/master/tck/features/LabelsAcceptance.feature#L57) suggest that openCypher implementations should be able to handle multiple labels.

2. The [`Create.feature`](https://github.com/opencypher/openCypher/blob/master/tck/features/Create.feature) and the [`CreateAcceptance.feature`](https://github.com/opencypher/openCypher/blob/master/tck/features/CreateAcceptance.feature) tests share some similar test cases (e.g. the first test case is identical). Is this intentional?

**Comment by Mats-SX** [comment]
1. Yes, multiple labels are supported. In Cypher's Property Graph Model, nodes may have zero or more labels, while relationships must have exactly one type. You can read more about labels in [the Neo4j manual](http://neo4j.com/docs/developer-manual/current/introduction/#graphdb-neo4j-labels).

2. No, that's not intentional. There's some overlap due to categorising issues. We would like to categorise scenarios into features in a good way, but we have some history to deal with. All features with names ending in `*Acceptance` are uncategorised (ie, keeps the categorisation of its source). Others (fewer) were created from scratch and/or categorised. There's no reason at all to keep duplicates, however, so I'll go ahead and delete that one (thanks!).

**Comment by szarnyasg** [comment]
Thanks for the quick reply!
