### ISSUE TITLE
Don't delete label after deleted all of nodes and relationships.

### ISSUE THREAD

**Issue by kienbui1995** [opencypher/openCypher#161]
how to remove all label in with a query?
I delete node and relationship before.

**Comment by Mats-SX** [comment]
Hello @kienbui1995 

I'm not positive that I understand your problem. Is the situation that you have a Neo4j database, in which you have deleted all nodes and relationships, and you are now looking to also delete the _tokens_ that Neo4j keeps as representations for labels and relationships?

If my interpretation is correct, I'm afraid the answer is that you can't. But that is not as bad as it sounds. These tokens existing in the database does not impact database performance or behaviour. If it is absolutely necessary, you could simply delete the database directory (default located in `data/databases/graph.db`), since your graph is empty already.

Should you have any additional problems with this situation, I think it would be more appropriate to raise an issue on the [Neo4j repository](https://github.com/neo4j/neo4j/issues), as this is more a database concern than a query language concern. From Cypher's point of view, a label or type does not exist if no entity (node or relationship) is associated with it.

**Comment by kienbui1995** [comment]
Sure. I will close this issue and yesterday  I created a issue on the Neo4j repository.
