### ISSUE TITLE
parameters not parsing

### ISSUE THREAD

**Issue by crichey** [opencypher/openCypher#163]
this query runs fine in the console and via BOLT but fails to parse with m03 grammar
`match(n:Person {name:{pname}}) return n order by n.name limit 10 ;`

produces these errors:
line 1:27 mismatched input '}' expecting {':', WHITESPACE}
line 1:28 extraneous input '}' expecting {')', WHITESPACE}

**Comment by Mats-SX** [comment]
Hello @crichey and thanks for reaching out to us.

The grammar is choking on your query because it is using the deprecated parameter syntax, with wrapping braces (`{}`). The new parameter syntax uses a leading dollar sign (`$`); see [this CIP](https://github.com/opencypher/openCypher/blob/master/cip/2.testable/CIP2016-07-07-Parameter-syntax.adoc) for more details.

Neo4j migrates this a bit slower, and will support the old syntax for at least `3.1`. (If you'd like the `M03` grammar to work, you could use the `legacy` version, which contains support for the deprecated parameter syntax.)

All the best
Mats
