### ISSUE TITLE
Strange behavior on simple query parsing using ANTLR4 grammar

### ISSUE THREAD

**Issue by fcofdez** [opencypher/openCypher#168]
Hi,
I'm using the latest stable antl4 grammar for some Cypher parsing and I found a strange behavior. 

Parsing the query:
`MATCH (e) return e` which is a pretty basic query I get:

```
line 1:7 no viable alternative at input '(e'
line 1:17 no viable alternative at input 'return e'
line 1:17 extraneous input 'e' expecting {<EOF>, WHITESPACE}
```

If I change the nodePattern `e` to `x` it works.

`MATCH (x) return x`

**Comment by Mats-SX** [comment]
Hi @fcofdez and thanks for reaching out to us!

Yes, that was indeed a bug (caused by bad lexing of `e` as part of exponential-form real numbers). Coincidentally, I just fixed it yesterday. I will publish another milestone release today, and hopefully you'll find that the issue is gone!

Please, do not hesitate to report further findings if you stumble upon them.

All the best
Mats
