### ISSUE TITLE
[Cypher Grammar] Migration notes 

### ISSUE THREAD

**Issue by FylmTM** [opencypher/openCypher#19]
Hi all,

I am author of Cypher plugin for Jebrains IDE's.
Initially I created Cypher grammar by porting `cypher-compiler` into `.bnf`.

Currently I am trying to migrate plugin to official Cypher grammar.

------

1) `Cypher = WS, AllOptions, WS, Statements ;`
Accordingly to this rule, we can't specify options for each statement. In my implementation it's possible to define options per-statement.

Looks like that `AllOptions` rule should be in `Statement` rule.
```
Statement = {AllOptions} (Command | Query);
```

2) `PRAGMA` rule. 
I have asked about this one and answer was "this is for internal use". 
Also I didn't find any information on internet about this clause.
Do we need this in grammar?

3) Consistency with using 'SP' rule. 
Let's take this rule for example:
```
Expression3 = Expression2, {
                ('[', Expression, ']')
              | ('[', [Expression], '..', [Expression], ']')
              | ('=~', Expression2) | ('IN', Expression2)
              | ('STARTS', 'WITH', Expression2)
              | ('ENDS', 'WITH', Expression2)
              | ('CONTAINS', Expression2)
              | ('IS', 'NULL')
              | ('IS', 'NOT', 'NULL')
            } ;
```
`SP` rule is not used here at all.
However if we look at this one:
```
CreateIndex = 'CREATE', SP, 'INDEX', SP, 'ON', NodeLabel, '(', PropertyKeyName, ')';
```
In this rule `SP` is used between every keyword.

-----

Overall - thank you for grammar!

**Comment by FylmTM** [comment]
Update.

4) `Expression1` rule has this part: `| ('COUNT', '(', '*', ')')`
This one conflicts with `| FunctionInvocation`.
Probably `count(*)` construct from Grammar perspective should be function invocation and * should be valid argument?

**Comment by Mats-SX** [comment]
Hello @FylmTM and apologies for the late reply!

The grammar specification as it stands today is a direct product of the neo4j parser implementation, and as such it has a few quirks that are really implementation details rather than language features. We do intend to amend these issues as we pass by them, and you raising them here is a great aid!

1) This is actually not a supported feature. A Cypher string may only carry one statement, and the reason the parser did something like this is to give a good error message when extra tokens were sent past the optional semicolon. `RETURN 1 ; RETURN 2` was never a valid Cypher query. We will simplify the grammar specification and remove these parsing rules.

2) No, we probably do not want this in the grammar. I've listed it for removal.

3) Yes, we are aware of lots of missing whitespace rules in the grammar as it stands today. I realise that since you posted this issue, we have done some work on this, and should be better off now. I doubt we have `SP` and `WS` in every place we should have, but we do intend to fill the holes. Please do report any missing or incorrect whitespace rules if you find any.

4) We haven't really considered the lexing/parsing distinction when designing the grammar. We did run into exactly this issue when working on the Anltr grammar spec, that we are also able to produce now. Cypher today does allow most keywords to be used as variables, but this can be solved in lexing by composition (see the generated Antlr grammar for how we solve this: https://github.com/opencypher/openCypher/blob/master/grammar/generated/Cypher.g4#L435). I'm sure that this behaviour needs different handling in differently designed parsers/lexers, so I'm not claiming this approach is universally applicable, but it works in this case.

Additionally, on 4), it's quite possible that we in the future will disallow using (some) keywords as variables. If you do want that to happen, I suggest opening an issue for that particular request, and we can have a focused discussion on the pros and cons of that there.

Thank you for your great work
Mats

**Comment by FylmTM** [comment]
Hi @Mats-SX ,

Thanks for the information. 
Also - Antlr4 grammar existence is amazing news for me. I am definitely going to try migrate Cypher plugin to Antlr4 grammar. Will see how it goes.

**Comment by Mats-SX** [comment]
Awesome! Good luck, and keep us posted.

Mats
