### ISSUE TITLE
Unobservable behavior in TCK test

### ISSUE THREAD

**Issue by zsambek** [opencypher/openCypher#221]
As a university project (under the supervision of @szarnyasg and @jmarton), I tried to implement the TCK tests on Neo4j. My first approach was to use Cypher queries to get the side-effects, but this turned out to be unfeasible, e.g. `CREATE (n) DELETE n` does not result in any observable behaviour. I then switched to using the [`QueryStatistics`](http://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphdb/QueryStatistics.html) class, which works fine for nodes using the `getNodesCreated()` and `getNodesDeleted()` methods. However, it does not provide method for retrieving properties.

```
  Scenario: Non-existent values in a property map are removed with SET =
    Given any graph
    And having executed:
      """
      CREATE (:X {foo: 'A', bar: 'B'})
      """
    When executing query:
      """
      MATCH (n:X {foo: 'A'})
      SET n = {foo: 'B', baz: 'C'}
      RETURN n
      """
    Then the result should be:
      | n                         |
      | (:X {foo: 'B', baz: 'C'}) |
    And the side effects should be:
      | +properties | 2 |
      | -properties | 1 |
```

**Comment by szarnyasg** [comment]
So, basically, our question is twofold:
1. what is the recommended approach for testing such behaviour?
2. what is the precise semantics of the `+properties` and `-properties` side effects?

For question 1, I believe we should only test side effect that can be observed with running standard openCypher queries. For example, I think if a user runs the query `CREATE (n) DELETE n` and the database does nothing, that classifies as a correct behaviour. Even if it does create and delete a node, the user has no way of telling whether this happened or not (except for extracting internal ids and making assumptions based on their values, but that is bad practice in general).

For question 2, I do not have an answer that is in sync with the [test case](https://github.com/opencypher/openCypher/blob/72603db1277038c681797abc8d163397166f7ba7/tck/features/SetAcceptance.feature#L269):
* If `properties` means _property keys_, then it should be `+1`, `-1`, as the `bar` key is dropped, while the `baz` key is added (and the `foo` key is kept).
* If `properties` means _property key-value pairs_, then it should be `+2`, `-2`, as the `foo: 'A'` and `bar: 'B'` are dropped, while `foo: 'B'` and `baz: 'C'` are added.
* If `properties` means _property values_, then it should be `+1`, `-1`, as the `'A'` is dropped, while `'C'` is added (and `'B'` is kept).

**Comment by Mats-SX** [comment]
For question 2:

The TCK was designed around Neo4j's capabilities with respect to reporting side effects. The `QueryStatistics` interface is indeed the model used for that. I modelled the properties symmetrically to the other elements in the TCK, but Neo4j can unfortunately not distinguish between removing and setting properties, because removing properties is implemented as setting them to `null`.

What we are doing is just adding the two property side effect values and comparing to the value returned from [`QueryStatistics#getPropertiesSet`](http://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphdb/QueryStatistics.html#getPropertiesSet--). You'll find the code for this in [`QueryStatisticsMatcher`](https://github.com/neo4j/neo4j/blob/3.2/enterprise/cypher/spec-suite-tools/src/main/java/cypher/feature/parser/matchers/QueryStatisticsMatcher.java).

So the interpretation in the TCK currently is a variant on your third bullet-point:

* `properties` means _property values_, without checking the value before writing (overwrite semantics)

----

Question 1 is more difficult. I'm not sure whether `doing nothing` is correct for `MATCH (n) DELETE n` -- possibly. For `MATCH (n) DELETE n RETURN n` it certainly is not. There's no specification currently on reporting of side effects, other than the `GraphStatistics` interface already mentioned. All TCK tests are modeled to fit that interface -- of course, this is certainly subject to change (or at least to specification).

**Comment by zsambek** [comment]
Thanks for your response.

For question 1, we thought about this test:

```
Scenario: Create and delete in same query
    Given an empty graph
    And having executed:
      """
      CREATE ()
      """
    When executing query:
      """
      MATCH ()
      CREATE (n)
      DELETE n
      """
    Then the result should be empty
    And the side effects should be:
      | +nodes | 1 |
      | -nodes | 1 |
```
The main problem is that I checked its internal id in Neo4j too, but it didn't change. Unfortunately from the outside it seems like nothing changed at all, although the Neo4j WebUI says that we created 1 node and deleted 1 node. 
My current solution to check side effects:
1. After the "And having executed" part I store the nodes in a List. (in our example: node<0>)
2. Affer the "When executing query" part I store the nodes in a List. (in our example: node<0>)
3. I check the positive and the negative differences between the two lists. 

As you can see my lists consist the "same" elements according its internal ids. What is the recommended approach for testing such behaviour?

**Comment by Mats-SX** [comment]
@zsambek I think that Neo4j _will_ reserve an internal id. I just tested it quickly and it seems to check out. Try `MATCH (n) RETURN max(id(n))` followed by `CREATE (n) DELETE n CREATE ()` then find ids again, and you'll see it will have 'jumped' one id.

Now, I'm not saying that the current approach to reporting side effects is a done deal. I think this is an interesting point that does warrant a wider discussion on what the best way of doing this is. Counting every creation/deletion of all the things that can be created/deleted in a Cypher statement is the naive approach that we currently are using, but perhaps changing the model to count the _impact_ on the graph, as a kind of delta-report, would be more fitting?

**Comment by szarnyasg** [comment]
@Mats-SX great idea. However, it does not work perfectly: for `CREATE (n) DELETE n` (without an additional `CREATE ()`), the returned value will not be increased, as we have just deleted the node with the maximum id.

As a hackish workaround, the following would work - run this query each time and subtract one from the difference.
```
CREATE (n) DELETE n RETURN id(n)
```
This allows us to observe the effect of `CREATE (n) DELETE n`.

I believe changing the model to only check "observable deltas" would be easier to comprehend and more straightforward to implement. I think this would be a good topic for discussion in [OCIM2](http://www.opencypher.org/event/2017/05/10/event-ocim2/)'s "openCypher Artifacts" session.

**Comment by Mats-SX** [comment]
I'm working on clearly defining this in an upcoming PR. One question that is not obvious to me is whether to link modification of properties to the containing entity. Consider this scenario:

```
Scenario: moving property between entity
  Given an empty graph
  And having executed:
    """
    CREATE ({prop: 1})
    """"
  When executing query:
    """
    MATCH (old)
    CREATE (new)
    SET new.prop = old.prop
    DELETE old
    """
  Then the result should be empty
  And the side effects should be:
    | +nodes | 1 |
    | -nodes | 1 |
```

Should the side effects regarding properties here list nothing, or plus one and minus one, since the property was copied from one entity to another?

**Comment by Mats-SX** [comment]
To further illustrate my argument, consider this scenario, where I've noted the side effects in alignment with my thinking.

```
Scenario: Copying property between entities
  Given an empty graph
  And having executed:
    """
    CREATE (:HasProp {prop: 1}), (:NoProp)
    """
  When executing query:
    """
    MATCH (h:HasProp)
    MATCH (n:NoProp)
    SET n.prop = h.prop
    REMOVE h.prop
    """
  Then the result should be empty
  And the side effects should be:
    | +properties | 1 |
    | -properties | 1 |
```

**Comment by szarnyasg** [comment]
#236 closes this issue, doesn't it?

**Comment by Mats-SX** [comment]
@szarnyasg Yes, that was the idea. Thanks!
