### ISSUE TITLE
Any In-Memory Graph implementations yet? 

### ISSUE THREAD

**Issue by cleemullins** [opencypher/openCypher#23]
Has anyone done an implemention of OpenCypher against a simple in-memory store?

**Comment by Mats-SX** [comment]
Hello @cleemullins and apologies for our late reply!

We do not know of any implementation of openCypher except for neo4j (https://github.com/neo4j/neo4j), which of course is where Cypher was born. We do intend on providing, as part of this open source project, a reference implementation of Cypher, and in this endeavour we will need some sort of graph backend for Cypher to communicate with. We don't know yet what form of backend this will be, but if I had to guess, a very simple in-memory graph seems a very good candidate.

All the best
Mats

**Comment by versae** [comment]
Not exactly Cypher but an extended subset for graph projections (before virtual nodes existed), [ProjX](http://davebshow.github.io/projx/getting-started/) runs in memory over the Python NetworkX library.

**Comment by jenmud** [comment]
I am have been working on a pure python in-memory graph database called [ruruki](https://www.github.com/optiver/ruruki). I am at the point where we are trying to get a query language implemented for it, and I was planning to introduce `openCypher` to it, and help would be greatly appropriated.

Please have a look, and constructive comments and contributions are welcome.

See Projects:
Ruruki: https://www.github.com/optiver/ruruki
Ruruki-docs: http://ruruki.readthedocs.org/en/master/
Ruruki-eye: https://www.github.com/optiver/ruruki-eye
Online simple demo: http://ruruki.com/vertices/0?levels=1

**Comment by Mats-SX** [comment]
@jenmud This sounds very exciting. What exactly is it you feel you are interested in getting help with? Also, what do you feel that you lack in regards to `openCypher`, that you would like to have in order for you to proceed with Cypher as QL for Ruruki? We are very happy to communicate with the community to guide our progress, and provide you with the pieces that you are missing for implementing Cypher on your platform.

Regards
Mats

**Comment by Mats-SX** [comment]
@jenmud I should also mention that posting this in the Google Groups mailing list could be useful for you: https://groups.google.com/forum/#!forum/opencypher

**Comment by jenmud** [comment]
Thanks for taking the interest @Mats-SX and responding to my comment. To answer your [comment](https://github.com/opencypher/openCypher/issues/23#issuecomment-203776715) earlier. I am not entirely sure where to begin and how to go about implementing openCypher. I am not really sure what is required. I have seen the **tck features** which will help, but other then that I am not really sure.

Any help or guidance will help.

I will also post my original comment to the suggested google groups, and hoping to get more traction.

Implementing the query language is the last peace of the puzzle before I am start focusing on other features and improvements. Having Cypher as the query language is important because I would use ruruki for prototyping and proof of concept or anything that requires temporary graph structure. Once people are happy with what they got, they can transfer the graph data to neo4j and there original queries will still hold true.

**Comment by Mats-SX** [comment]
Very good, @jenmud. We will make sure to continue the conversation in the mailing list. (To anyone else reading this, please note that the mailing list is completely open for anyone to read or post: https://groups.google.com/forum/#!forum/opencypher)

**Comment by Mats-SX** [comment]
I'm closing this as answered now. If anyone has any follow-up topics to discuss, please open a new issue.

**Comment by j6k4m8** [comment]
Sorry to bring up an old thread, but this was an enormously helpful comment thread when I was searching around for options, and so I wanted to chime in.

My team recently started [a partial implementation of the Cypher spec](https://github.com/aplbrain/grand-cypher) for in-memory NetworkX-backed graphs (or sqlite-backed, through some of our other open source tools).

Grand-Cypher is compatible with [Grand](https://github.com/aplbrain/grand), which means it's also useful for querying data stored in sqlite or even dynamodb. It's not critical-path for our research, but I do try to keep an eye on the repo and field pull-requests or bug reports! Always happy to chat.

**Comment by Mats-SX** [comment]
And missing from this thread is also the official (but perhaps a bit dated) list at opencypher.org: https://opencypher.org/projects/
