### ISSUE TITLE
Questions about StringListNullOperatorExpression

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#321]
I was looking into the `StringListNullOperatorExpression` grammar clause with @marci543 and we had a few minor questions.

The relevant snippet of the grammar XML is the following:

https://github.com/opencypher/openCypher/blob/15157c0fe4243da1cbfe2c372bcd00fec77a5c17/grammar/basic-grammar.xml#L239-L263

1. The part `<seq> &WS; [ <opt>&expr;</opt> .. <opt>&expr;</opt> ] </seq>` would allow a list to be indexed as `some_list[..]`. This is not a valid expression. A workaround could be to enumerate all valid cases (only lower bound, only upper bound, both lower and upper bounds). This might be more trouble than worth though.

2. We didn't find the name `StringListNullOperatorExpression` very intuitive. Does it mean something like "string operator, list indexer or null check"?

**Comment by Mats-SX** [comment]
1. You're correct. This grammar allows something which is semantically invalid, and relies on a subsequent check that at least one of the bounds is present.

2. I agree that it isn't intuitive. I had to stop and think for a while why I named it like that when I read this issue. The history here is that all these nested expression forms were called `expression1`, `expression2`, etc which was even less informative (although possibly less confusing). This one was named like this because it is the expression rule for string operators (`STARTS WITH`, `ENDS WITH`, `CONTAINS`), list operators (`IN`, list index `[1]`) and null operators (`IS NULL`, `IS NOT NULL`). I'm happy to consider alternatives in naming.

**Comment by szarnyasg** [comment]
Re 2, two ideas:

* It could be called `StringOrListOrNullOperatorExpression` - but I am not sure this helps much.
* The production rule could be split to 3 subrules (e.g. `StringOperatorExpression`, `ListOperatorExpression`, `NullOperatorExpression`). This would have the side-effect that the generated artifacts (railroad diagram/ANTLR) would have these subexpressions as well which would make them clearer (but also add extra elements).

**Comment by Mats-SX** [comment]
I would say the splitting out idea is the better alternative. I'm wondering if this has any consequence on the subject of operator precedence, but I can't see how.
