### ISSUE TITLE
Parse error of "start/call" using ANTLR4 grammar

### ISSUE THREAD

**Issue by wangtao9** [opencypher/openCypher#343]
Hi,
Similar to #168 , When I parse the following query using ANTLR4 gramar:
`match(start) return start`
I get:
`line 2:6 no viable alternative at input 'match(start'`

The following queries will also cause similar errors:
```
match(call) return call
match(n:call) return n
match(n)-[:call]->(m) return m
```
While I change the nodePattern `start/call` to `x` it works.

**Comment by thobe** [comment]
For compatibility between implementations, keywords (such as `start` and `call` in this case) should not be used as identifier names. The Neo4j implementation(s) happens to be able to handle this because it uses a non-traditional parser that does not use a lexer, but they are the odd ones.

If one really want to use keywords as identifiers, they can be escaped like this: 

    MATCH (`start`) RETURN `start`

    MATCH (n:`call`) RETURN n

    MATCH (n)-[:`call`]->(m) RETURN m

It would be possible to change this so that the grammar explicitly allows keywords as identifiers, but since such queries often get very difficult to read, it is questionable whether this is a valuable thing to do.
