### ISSUE TITLE
Result order is not enforced in TCK VarLengthAcceptance scenarios

### ISSUE THREAD

**Issue by jeffreylovitz** [opencypher/openCypher#370]
Scenarios like https://github.com/opencypher/openCypher/blob/master/tck/features/VarLengthAcceptance.feature#L69 return multiple results, but do not use an `ORDER BY` clause to enforce a sort order.

To my knowledge, the sequence of results is not guaranteed to be deterministic without this clause.

I've made a branch that adds an ORDER BY clause to all scenarios in this feature that return multiple results, and updated the expected results appropriately.

If this seems like a sensible change, let me know and I will open a PR!

**Comment by thobe** [comment]
The scenarios in `VarLengthAcceptance.feature` does not use `ORDER BY` to enforce a sort order, nor are they intended to assert on a sort order. If the order of the results is important the scenario will specify this as `Then the result should be, in order:`, since the scenario only states `Then the result should be:`, that is intended to mean that any order is accepted.

I agree that this could be made more explicit in the scenario definition, for example by stating `Then the result should be, in any order:`.

**Comment by Mats-SX** [comment]
I agree with @thobe, and I would like to add that I think if you would like to provide a set of ordered var-length scenarios (with assertions on order) we would be happy to review those as a TCK addition.

**Comment by jeffreylovitz** [comment]
Thanks, @thobe and @Mats-SX !

I hadn't noticed the distinction between the `Then the result should be:` and `Then the result should be, in order:` acceptance parameters.

I've opened PR #371 with enforced ordering as described in my original post, but I agree that a more explicit definition like `Then the result should be, in any order:` may be a more robust solution.
