### ISSUE TITLE
Reload data from elastic using scrollid in cypher? 

### ISSUE THREAD

**Issue by apremgeorge** [opencypher/openCypher#397]
Hi
I load data from Elasticsearch, using scrollid,
```
CREATE CONSTRAINT ON (cus:Customer) ASSERT cus.CIN IS UNIQUE
CREATE CONSTRAINT ON (mer:Merchant) ASSERT mer.MerchantDetailsLocation IS UNIQUE​

CALL apoc.es.query("http://localhost:9200",'index','doc','size=100&scroll=5m',null) yield value with value._scroll_id as scrollId, value.hits.hits as hits​
UNWIND hits as hit​
UNWIND hit._source AS trans​
MERGE (C1:Customer {CIN: trans.CIN})​
MERGE (M1:Merchant {MerchantName: dctrans.MerchantDetailsLocation})​
MERGE (C1)-[:Transfered {CardNo: trans.CardNo, TxnAmount: trans.TxnAmount, UniqueId: trans.UniqueId} ]->(M1)​
​
WITH range(101,10000,100) as list, scrollId​
UNWIND list as count​
CALL apoc.es.get("http://localhost:9200","_search","scroll",null,{scroll:"5m",scroll_id:scrollId},null) yield value with value._scoll_id as scrollId, value.hits.hits as nextHits​
UNWIND nextHits as hit​
UNWIND hit._source AS trans​
MERGE (C1:Customer {CIN: trans.CIN})​
MERGE (M1:Merchant {MerchantName: dctrans.MerchantDetailsLocation})​
MERGE (C1)-[:Transfered {CardNo: trans.CardNo, TxnAmount: trans.TxnAmount, UniqueId: trans.UniqueId} ]->(M1)​
​return C1, M1​
```
I have set Constraint to two nodes, Customer and Merchant, Customer did transfer as a relation

In Elastic I have 1million data,

Initially I loaded 10,000 using above code loading 100 at a time, then if I run the same code again to fetch another 10,000, it duplicates the relation again for the first 10,000 and goes to next 10,000.

So I have two Questions
1. In order to avoid the relation to duplicate, may I know how to set constraint for the relation based on its property, I have properties in relation where the UniqueId is unique
     I tried CREATE CONSTRAINT ON ()-[r:Transfered]-() ASSERT r.UniqueId IS UNIQUE; but not working

2. if possible, May I know how to save the scroll id for later use, so that I can run the 2nd segment only to fetch the 2nd 10,000 data?

Thanks in Advance

**Comment by thobe** [comment]
Hi @apremgeorge,

Since your question is about the ElasticSearch integration in the Neo4j APOC library, I think you should ask the developers of those procedures instead. I believe the best forum for getting answers to such questions would be the Neo4j Community site, specifically in the APOC category: https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc/77
Or you could look at the github project page for APOC for links: https://github.com/neo4j-contrib/neo4j-apoc-procedures

I will close this issue, since it is not relevant for the specification of the Cypher query language, which is what this repository is about. I hope you get answers on one of those other forums.
