### ISSUE TITLE
A handful of TCK feature specifications use problematic Gherkin syntax 

### ISSUE THREAD

**Issue by eastlondoner** [opencypher/openCypher#398]
Some of the features in the TCK use syntax like
```
Background:
    Given any graph

  Scenario: My Scenario
    And something has been done to my graph
    When ...
    Then ...
```

Parsing these cases fails with a syntax error when I try and use it with a rust implementation of the Gherkin parser. The parser I am using does not accept starting a scenario with an `And`. I believe that this is not really correct Gherkin, even if some parsers may tolerate it. The examples in the Gherkin reference do not use `And` in this way - they always begin a Scenario with `Given` when there is a preceding `Background` clause. e.g. https://cucumber.io/docs/gherkin/reference/#background

This only occurs in the following files:
```
ExpressionAcceptance.feature
LabelsAcceptance.feature
MergeIntoAcceptance.feature
OptionalMatchAcceptance.feature
SkipLimitAcceptance.feature
StartsWithAcceptance.feature
TemporalAccessorAcceptance.feature
TemporalArithmeticAcceptance.feature
TernaryLogicAcceptance.feature
VarLengthAcceptance.feature
```

**Comment by Mats-SX** [comment]
That's odd. The way I interpret `Background` is that it inserts the specified steps at the beginning of every scenario; the scenarios thus do not start with `And`, they all start with the `Given` from the `Background`. It really makes sense to me as that kind of 'factor-out' feature.

However, since it is used in this way it would be easy to fix the violation by simply inlining the `Background` steps into all scenarios in the file. There are probably also readability advantages for doing that, even though verbosity will suffer.

**Comment by Mats-SX** [comment]
Here is a reference of examples where scenarios directly start with `Then`: https://relishapp.com/cucumber/cucumber/docs/gherkin/background

Is that allowed in your Rust parser?

**Comment by eastlondoner** [comment]
@Mats-SX Starting with `When` or `Then` is fine. It's the `And` it doesn't like - it cannot determine for itself what it's an `And` of.

I think inlining the `Background` might be a bit much, idk? - changing the initial `And` to be a `Given` is sufficient. i.e.

```
Background:
    Given any graph

  Scenario: My Scenario
    Given something has been done to my graph
    When ...
    Then ...
```

**Comment by Mats-SX** [comment]
I'm not sure if that would make sense. The model for the TCK is to use Gherkin syntax to suggest a rather rigid test scenario structure, using only very [few predefined steps](https://github.com/opencypher/openCypher/blob/master/tools/tck-api/src/main/scala/org/opencypher/tools/tck/constants/TCKStepDefinitions.scala) that are designed to be easy to read and understand.

Your suggestion would mean that we either

a) invent a new `Given` step that somehow models the same semantics as a current `Given` and `And` at the same time
b) alias a (or all) current `And` steps to `Given` steps that have the same effect

a) would mean we could get rid of `Background` entirely
b) would mean I could write both of these equivalent scenarios:

```
Scenario: foo
  Given an empty graph
  Given having executed:
    """
    CREATE (:Foo)
    """
  /* more */
```

```
Scenario: foo
  Given an empty graph
  And having executed:
    """
    CREATE (:Foo)
    """
  /* more */
```

I admit that in early design I was unaware that multiple `Given` steps were allowed, hence reaching for `And` for the additional setup operations. These could have been `Given` steps all along. (In fact, that seems to be true for all `And` steps?)

I rather like the progression of a single `Given` followed by a sequence of `And`s, then a sequence of `When`/`Then` pairs. Thus I think I would argue to remove `Background` altogether and just inline the `Given`s.

@hvub What do you think?

**Comment by eastlondoner** [comment]
either is fine by me 👍

**Comment by hvub** [comment]
To my latest perception, `Background` is more an obstacle than a helper. From the categorization work, I see that people mainly think about scenarios as a self-contained things. They simply for get about a background declaration (to you readability point @Mats-SX ). There are also feature files with a `Background` and some scenarios that do not make use of the `Background`, which is another evidence point for me that `Background` is more confusing than helpful. `Background` is a helper for the writer of scenarios but not for the reader. However, TCK scenarios should be optimized for reading, because they are much more read than written. 

Hence, I think it would be a positive to inline all backgrounds. I have create a card for that.

**Comment by Mats-SX** [comment]
I am in favour.

**Comment by hvub** [comment]
During categorization we have removed all backgrounds, I think. M16 should have no backgrounds anymore. If there you one some, report it as a new issue. I will close this issue.
