### ISSUE TITLE
Map formatting

### ISSUE THREAD

**Issue by AviAvni** [opencypher/openCypher#435]
Why there is no space between : to ' in this test result?
https://github.com/opencypher/openCypher/blob/35f7e54042eadeac33c5986c91cf1e0b1a528a70/tck/features/expressions/literals/Literals6.feature#L217

**Comment by Mats-SX** [comment]
While there is no semantic meaning to whitespace between symbols in Cypher (although at least one is often required), the [style guide](url) suggests that the map you reference should look like this:

```
{a: ' { b : ', c: {d: ' '}, d: ' } '}
```

which it doesn't, so thanks for raising our attention to it.

It isn't straight-forward to properly style this map manually since the literal string values look like map syntax themselves. However, all characters within the string delimiters (`'`) should of course be retained verbatim from the query expression.
