### ISSUE TITLE
NULL token name is a reserved word in C++

### ISSUE THREAD

**Issue by oodame** [opencypher/openCypher#536]
Hi,
When I use the Cypher.g4 to generate a C++ parser by Antlr4, I found that `NULL` token happens to be a reserved word in C++. And the generated parser is as below
![image](https://user-images.githubusercontent.com/106443070/179535560-36a4fbd6-b408-4a40-99af-2ecc04dad692.png)
which will get a compile error.

So how about change the `NULL` token name to `NULL_LITERAL`?

**Comment by tobias-johansson** [comment]
It seems ANTLR4 has support for [escaping reserved words](https://github.com/antlr/antlr4/issues/1070), but `"NULL"` is not in its [list of reserved words for cpp](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/codegen/target/CppTarget.java#L41), as far as I understand.

Rather than changing the openCypher grammar, and possibly breaking other consuming code, I'd suggest raising an issue on the ANTLR generator.

**Comment by oodame** [comment]
Thanks for your reply, and it's indeed more suitable for an issue on the ANTLR generator.
